### ISSUE TITLE
About the toc

### ISSUE THREAD

**Issue by aborruso** [ironmeld/markdown-publishing-guide#1]
Hi,
I have created a RTD website in markdown. This is an example page https://ciao-mondo.readthedocs.io/it/latest/README.html

I have created an [index file](https://github.com/pigreco/HfcQGIS/blob/master/index.rst) using your template, but I have no rendering https://ciao-mondo.readthedocs.io/it/latest/index.html

What's wrong in my settings?

Thank you

**Comment by rick-masters** [comment]
Hello aborruso. I'm sorry for the very long delay in my reply. I was away for a while and did not foresee support issues with this project. I should have documented some troubleshooting tips and left a note about my limited ability to provide support.

My intent with this project was to show a small example of a working index so that others could use that as a starting point for something bigger and more useful. You could call it a "Hello World" example. I documented this minimal example because I was not able to find a minimal example in any documentation.

Anyway, I'm afraid your project is different in structure and sophistication from my simple example. Adapting this small working example to your situation will probably take a bit of troubleshooting on your part.

I recommend that you copy your project to a different name so you can start hacking around without affecting your original project. You would use this new project just for troubleshooting, in order to figure out what the problem is, and then you can delete it later. You would also create a corresponding copy of the project over on readthedocs for troubleshooting.

The troubleshooting strategy I will suggest is to start stripping away the differences between your new copy of your project and my simple example until the specific difference causing the problem is identified. Just start guessing as to what it could be. For example, your conf.py file has a lot more configuration than mine.  Maybe thats causing a problem for read the docs.
Try removing the extra configuration lines in chunks until it (the RTD index) works or your file is just like mine. You may also need to adapt or remove your content if you are relying on that configuration.
Try removing files in your index.rst until it works or your index is pretty much like mine. 
Try moving files into the docs subdirectory so it is more like my setup.
Try removing unusual content from your markdown docs.
Try changing the content to be more like mine.

At this point you are just trying to figure out what difference, if removed, causes the index to show up correctly. This process basically has to work because you either find the problem or you eventually end up with two projects that are essentially identical although one works (mine) and one doesn't (yours). In my experience, that's so rare that it is not worth worrying about until it happens.

Once the difference that is causing the problem is identified, it is likely that there will be a straightforward solution that can be applied back to your original project.

Anyways, hope this helps. Sorry again for the delay. I'll work on including more support information into this project going forward.

**Comment by rick-masters** [comment]
I have added troubleshooting information to the document and also clarified that the instructions are intended for new documents.
